name: auto generate hosts file

on:
  push:
  schedule:
    - cron: '0/10 * * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependence
        run: npm i -g pnpm && pnpm i

      - name: generate by hosts-generator
        run: npm run g

      - name: update Readme.md
        run: npm run docs

      - name: commit the generated hosts files
        run: |
          git config --global user.email "eyelly.wu@gmail.com"
          git config --global user.name "Eyelly Wu"  
          git add .
          git commit -m 'chore: update hosts'

      - name: git push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUBLISH_TOKEN }}
